In [5]:
!pip install geopandas

Requirement already satisfied: geopandas in /usr/local/lib/python3.7/dist-packages (0.9.0)
Requirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.7.1)
Requirement already satisfied: pyproj>=2.2.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (3.1.0)
Requirement already satisfied: fiona>=1.8 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.8.20)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.1.5)
Requirement already satisfied: munch in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2.5.0)
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (7.1.2)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.1.1)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (57.2.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2021.5.30)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (21.2.0)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (0.7.2)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (2018.9)

In [6]:
!wget https://raw.githubusercontent.com/StratagemGIS/files/main/Canadian%20Roads.zip
!wget https://raw.githubusercontent.com/StratagemGIS/files/main/Canadian%20Provinces.zip
!wget https://raw.githubusercontent.com/StratagemGIS/files/main/Canadian%20BusStops.zip

--2021-07-28 21:55:08--  https://raw.githubusercontent.com/StratagemGIS/files/main/Canadian%20Roads.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2345031 (2.2M) [application/zip]
Saving to: ‘Canadian Roads.zip.1’

Canadian Roads.zip. 100%[===================>]   2.24M  --.-KB/s    in 0.06s

2021-07-28 21:55:08 (39.4 MB/s) - ‘Canadian Roads.zip.1’ saved [2345031/2345031]

--2021-07-28 21:55:08--  https://raw.githubusercontent.com/StratagemGIS/files/main/Canadian%20Provinces.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2453582 (2.3M) [application/zip]
Saving to: ‘Canadian Provinces.zip.1’

Canadian Provinces. 100%[===================>]   2.34M  --.-KB/s    in 0.06s

2021-07-28 21:55:08 (41.4 MB/s) - ‘Canadian Provinces.zip.1’ saved [2453582/2453582]

--2021-07-28 21:55:08--  https://raw.githubusercontent.com/StratagemGIS/files/main/Canadian%20BusStops.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2166247 (2.1M) [application/zip]
Saving to: ‘Canadian BusStops.zip.1’

Canadian BusStops.z 100%[===================>]   2.07M  --.-KB/s    in 0.02s

2021-07-28 21:55:09 (115 MB/s) - ‘Canadian BusStops.zip.1’ saved [2166247/2166247]

In [7]:
import geopandas as gpd

In [8]:
canadian_provinces = gpd.read_file('zip://Canadian Provinces.zip!Canadian Provinces')
canadian_roads = gpd.read_file('zip://Canadian Roads.zip!Canadian Roads')
canadian_busstops = gpd.read_file('zip://Canadian BusStops.zip!Canadian BusStops')

In [10]:
print(canadian_provinces.shape)

(13, 4)

In [13]:
canadian_provinces

    ID  ...                                           geometry
0    1  ...  POLYGON ((-806053.365 1299778.135, -1087787.37...
1    2  ...  MULTIPOLYGON (((-2056047.437 394083.602, -2055...
2    3  ...  MULTIPOLYGON (((357626.075 880201.105, 357475....
3    4  ...  MULTIPOLYGON (((2210266.145 -9603.475, 2210081...
4    5  ...  MULTIPOLYGON (((2987714.014 760037.474, 298890...
5    6  ...  MULTIPOLYGON (((-1494081.226 2608032.631, -149...
6    7  ...  MULTIPOLYGON (((2352014.325 -75437.602, 235267...
7    8  ...  MULTIPOLYGON (((939490.813 947866.664, 939790....
8    9  ...  MULTIPOLYGON (((1601780.617 -188407.966, 16032...
9   10  ...  MULTIPOLYGON (((2431397.215 298275.781, 243111...
10  11  ...  MULTIPOLYGON (((1605711.688 -189202.988, 16056...
11  12  ...  POLYGON ((-486516.835 1238768.481, -378901.679...
12  13  ...  MULTIPOLYGON (((-1522791.377 2684442.459, -152...

[13 rows x 4 columns]

In [16]:
canadian_provinces.crs

<Projected CRS: EPSG:3978>
Name: NAD83 / Canada Atlas Lambert
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Canada - onshore and offshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon.
- bounds: (-141.01, 40.04, -47.74, 86.46)
Coordinate Operation:
- name: Canada Atlas Lambert
- method: Lambert Conic Conformal (2SP)
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [23]:
canadian_busstops.sample(5)

                           Name                         geometry
50399    River / Nicolls Island  POINT (1516389.374 -188060.527)
10078        Humboldt at Quadra  POINT (-2035051.431 396666.764)
60343      Beach Grove/Maypoint   POINT (2380576.240 301439.869)
15870  East Saanich at McTavish  POINT (-2028893.019 419716.365)
54879        McIntyre / McBrine  POINT (1195963.437 -492537.990)

In [22]:
canadian_roads.sample(5)

               Median  ...                                           geometry
5700   Without Median  ...  LINESTRING (-610407.687 375527.941, -609517.33...
10397  Without Median  ...  LINESTRING (1423623.693 313553.496, 1422965.54...
1961   Without Median  ...  LINESTRING (-611617.323 703114.461, -612462.25...
11047  Without Median  ...  LINESTRING (-257076.678 65935.786, -256203.911...
4129             None  ...  LINESTRING (-402095.414 476784.181, -401997.19...

[5 rows x 4 columns]